@if($errors->any())
<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>
@endif
<div class="row g-3">
  <div class="col-md-6"><label class="form-label">Nom de l’équipement <span class="text-danger">*</span></label><input name="nom" class="form-control" required maxlength="150" value="{{ old('nom', $equipement->nom ?? '') }}" placeholder="Ex. Réfrigérateur"></div>
  <div class="col-md-6"><label class="form-label">Type <span class="text-danger">*</span></label><select name="type" class="form-select" required><option value="">Sélectionnez un type</option><option value="frigo" @selected(old('type', $equipement->type ?? '') === 'frigo')>Réfrigérateur</option><option value="medicament" @selected(old('type', $equipement->type ?? '') === 'medicament')>Médicament à conserver</option><option value="ventilateur" @selected(old('type', $equipement->type ?? '') === 'ventilateur')>Ventilateur</option><option value="appareil_medical" @selected(old('type', $equipement->type ?? '') === 'appareil_medical')>Appareil médical</option></select></div>
  <div class="col-md-6"><label class="form-label">Niveau de sensibilité <span class="text-danger">*</span></label><select name="niveau_sensibilite" class="form-select" required>@foreach($niveaux as $niveau)<option value="{{ $niveau }}" @selected(old('niveau_sensibilite', $equipement->niveau_sensibilite ?? 'moyen') === $niveau)>{{ ucfirst($niveau) }}</option>@endforeach</select></div>
  <div class="col-md-6 d-flex align-items-end"><div class="form-check form-switch mb-2"><input type="hidden" name="actif" value="0"><input class="form-check-input" type="checkbox" name="actif" value="1" @checked(old('actif', $equipement->actif ?? true))><label class="form-check-label">À surveiller actuellement</label></div></div>
  <div class="col-12"><label class="form-label">Description et précautions</label><textarea name="description" class="form-control" rows="4" maxlength="2000" placeholder="Décrivez les précautions utiles en cas de coupure ou de forte chaleur.">{{ old('description', $equipement->description ?? '') }}</textarea></div>
</div>
<div class="mt-4 d-flex gap-2"><button class="btn btn-primary"><i class="bi bi-save me-1"></i>Enregistrer</button><a href="{{ route('front.equipements_sensibles.index') }}" class="btn btn-outline-secondary">Annuler</a></div>
